---

- stat:
    path: /usr/bin/dokku
  register: dokku

- name: Install Dokku dependencies
  apt:
    name: {{ dependencies }}
    state: present
    update_cache: true
  become: true

- block:
    - apt_key: url=https://packagecloud.io/gpg.key state=present

    - name: Add dokku repository
      apt_repository:
        repo: "{{ dokku_repo }}"
        state: present

    - shell: echo "dokku dokku/web_config boolean false" | debconf-set-selections
    - shell: echo "dokku dokku/skip_key_file boolean true" | debconf-set-selections

    - name: Install dokku
      apt:
        name: dokku
        state: latest
        update_cache: true

  when: not dokku.stat.exists
  
- shell: dokku plugin:install-dependencies --core || true
  ignore_errors: true

- shell: dokku plugin:install https://github.com/dokku/dokku-letsencrypt.git || true
  ignore_errors: true

- shell: dokku plugin:install https://github.com/dokku/dokku-postgres.git postgres || true
  ignore_errors: true

- shell: dokku plugin:install https://github.com/dokku/dokku-redis.git redis || true
  ignore_errors: true
